version: "3"
services:
  postgres:
    container_name: postgres
    image: debezium/postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
